# Generated by ChengetAi Deploy v3 from deployment.yml — DO NOT EDIT BY HAND.
# {{CADDY_SITE}} — automatic HTTPS via Let's Encrypt when the domain is public
# and ssl is enabled. Routing is derived from the deployment config.
{{CADDY_SITE}} {
    encode gzip

    # REST API keeps its /server path on the backend.
    @rest path /server /server/*
    reverse_proxy @rest dspace:{{REST_PORT}}

    # Everything else goes to the Angular UI.
    reverse_proxy dspace-angular:{{UI_PORT}}
}
