# Generated by ChengetAi Deploy v3 — Angular UI config (no IPs).
ui:
  ssl: {{HTTPS}}
  host: {{DOMAIN}}
  port: {{PUBLIC_PORT}}
  nameSpace: /
rest:
  ssl: {{HTTPS}}
  host: {{DOMAIN}}
  port: {{PUBLIC_PORT}}
  nameSpace: /server
