# Generated by ChengetAi Deploy v3 from deployment.yml — DO NOT EDIT BY HAND.
# No hardcoded IPs or domains: every value comes from the master config.
# Docker assigns the subnet (no fixed 172.x); Caddy is the only public port.
name: chengetai-{{DEPLOY_ID}}

networks:
  net:

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
    networks: [net]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dspace"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 30s

  dspacesolr:
    image: dspace/dspace-solr:latest
    restart: unless-stopped
    networks: [net]
    volumes:
      - solr:/var/solr/data

  dspace:
    image: dspace/dspace:latest
    restart: unless-stopped
    depends_on:
      dspacedb:
        condition: service_healthy
    environment:
      # Public URLs come from the domain, never an IP.
      - dspace__P__dir=/dspace
      - dspace__P__server__P__url={{SERVER_URL}}
      - dspace__P__ui__P__url={{PUBLIC_URL}}
      - dspace__P__name={{INSTITUTION}}
      - db__P__url=jdbc:postgresql://dspacedb:5432/dspace
      - db__P__username=dspace
      - db__P__password={{POSTGRES_PASSWORD}}
      - solr__P__server=http://dspacesolr:8983/solr
      - rest__P__cors__P__allowed__D__origins={{PUBLIC_URL}}
    networks: [net]
    volumes:
      - assetstore:/dspace/assetstore

  dspace-angular:
    image: dspace/dspace-angular:latest
    restart: unless-stopped
    depends_on: [dspace]
    environment:
      - DSPACE_REST_SSL={{HTTPS}}
      - DSPACE_REST_HOST={{DOMAIN}}
      - DSPACE_REST_PORT={{PUBLIC_PORT}}
      - DSPACE_REST_NAMESPACE=/server
      - DSPACE_UI_SSL={{HTTPS}}
      - DSPACE_UI_HOST={{DOMAIN}}
      - DSPACE_UI_PORT={{UI_PORT}}
    networks: [net]

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on: [dspace, dspace-angular]
    # The only public entrypoint. Caddy terminates TLS and proxies internally,
    # so the app ports are never exposed on the host.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [net]

volumes:
  pgdata:
  solr:
  assetstore:
  caddy_data:
  caddy_config:
