# Generated by ChengetAi Deploy v3 — DSpace backend config (no IPs).
dspace.dir = /dspace
dspace.server.url = {{SERVER_URL}}
dspace.ui.url = {{PUBLIC_URL}}
dspace.name = {{INSTITUTION}}

db.url = jdbc:postgresql://dspacedb:5432/dspace
db.username = dspace
db.password = {{POSTGRES_PASSWORD}}

solr.server = http://dspacesolr:8983/solr

rest.cors.allowed-origins = {{PUBLIC_URL}}
