#!/usr/bin/env bash
# DSpace 8 platform plugin for ChengetAi Deploy.
# Sourced by lib/utils.sh:load_plugin — requires DEPLOY_DIR, DEPLOY_NAME and
# the profile variables (INSTITUTION, ADMIN_EMAIL, ...) to be set.
#
# ChengetAi Deploy is an ORCHESTRATOR. The canonical DSpace deployment
# lives in the Bulawayo Polytechnic DSpace repository; this plugin never
# duplicates that logic. Per deployment it:
#
#   clone      the reference repository into deployments/<name>/engine/
#   configure  ports, instance name, admin account, generated DB secret
#              (via the environment contract the reference repo supports)
#   brand      copy deployments/<name>/branding/ over the engine assets
#   deploy     run the reference repository's install.sh
#   verify     the installer waits for the backend health endpoint
#   maintain   start/stop/status/logs/backup/restore/update/remove below

# shellcheck disable=SC2034  # PLUGIN_* consumed by the CLI after sourcing
PLUGIN_NAME="dspace"
PLUGIN_DESCRIPTION="DSpace 8 institutional repository"
PLUGIN_STATUS="available"

# The canonical DSpace deployment implementation.
ENGINE_REPO="https://github.com/wgmasvix-hue/bulawayo-polytechnic-dspace-.git"
ENGINE_BRANCH="claude/dspace-deployment-review-48qeth"

# Database credentials inside the dspacedb container
# (dspace/dspace-postgres-pgcrypto defaults; the password is generated by
# the reference installer and lives in the engine's .env, chmod 600).
DB_USER="dspace"
DB_NAME="dspace"

engine_dir() {
    echo "$DEPLOY_DIR/engine"
}

branding_dir() {
    echo "$DEPLOY_DIR/branding"
}

ui_port() {
    echo "${UI_PORT:-4000}"
}

rest_port() {
    echo "${REST_PORT:-8080}"
}

require_engine() {
    if [ ! -d "$(engine_dir)/.git" ]; then
        error "Deployment '$DEPLOY_NAME' has not been deployed yet. Run: chengetai deploy $DEPLOY_NAME"
    fi
}

# All compose operations run against the reference repository's campus
# stack, namespaced per deployment so data volumes never collide.
# (The reference stack uses fixed container names, so only one DSpace
# deployment can be RUNNING per server; volumes stay separate.)
pcompose() {
    docker compose -p "chengetai-$DEPLOY_NAME" \
        -f "$(engine_dir)/docker-compose-campus.yml" \
        --project-directory "$(engine_dir)" "$@"
}

plugin_server_ip() {
    local ip
    ip=$(grep -s '^SERVER_IP=' "$(engine_dir)/.env" | cut -d= -f2)
    echo "${ip:-localhost}"
}

plugin_urls() {
    local ip
    ip=$(plugin_server_ip)
    echo "  UI (browser):  http://${ip}:$(ui_port)"
    echo "  REST API:      http://${ip}:$(rest_port)/server"
}

# Create or reset the DSpace administrator against the already-running
# backend — no redeploy needed. Non-interactive when ADMIN_EMAIL and
# ADMIN_PASS are set, otherwise runs DSpace's own interactive prompt. This
# is what recovers from the "passwords do not match" case cleanly.
plugin_admin() {
    require_engine
    if ! container_running dspace; then
        error "The backend container (dspace) is not running. Start it first: chengetai start $DEPLOY_NAME"
    fi
    local lang="${ADMIN_LANG:-en}"
    if [ -n "${ADMIN_EMAIL:-}" ] && [ -n "${ADMIN_PASS:-}" ]; then
        info "Creating/updating administrator $ADMIN_EMAIL (non-interactive)..."
        if docker exec dspace /dspace/bin/dspace create-administrator \
                -e "$ADMIN_EMAIL" \
                -f "${ADMIN_FIRST_NAME:-Repository}" \
                -l "${ADMIN_LAST_NAME:-Admin}" \
                -c "$lang" \
                -p "$ADMIN_PASS"; then
            echo ""
            info "Administrator ready: $ADMIN_EMAIL"
            echo "  Sign in at: http://$(plugin_server_ip):$(ui_port)"
        else
            error "create-administrator failed (see the output above)."
        fi
    else
        info "Launching DSpace's interactive administrator setup..."
        echo "  Tip: set ADMIN_EMAIL and ADMIN_PASS (or pass --email/--password)"
        echo "       to run this without any prompts."
        echo ""
        docker exec -it dspace /dspace/bin/dspace create-administrator
    fi
}

# ── ORCID integration ───────────────────────────────────────────────────────
# Enable "Sign in with ORCID" + researcher-identity linking on a running
# DSpace, or report/disable it. The campus stack bind-mounts ONLY local.cfg
# into the backend, so every setting (including the auth-stack override that
# adds OrcidAuthentication) is written there; a `restart dspace` applies it.
ORCID_MARK_BEGIN="# >>> ChengetAi ORCID (managed — do not edit between these markers) >>>"
ORCID_MARK_END="# <<< ChengetAi ORCID (managed) <<<"

# Remove the managed ORCID block from a local.cfg (idempotent, no-op if absent).
_orcid_strip() {
    local cfg="$1" tmp
    tmp="$(mktemp)"
    awk -v b="$ORCID_MARK_BEGIN" -v e="$ORCID_MARK_END" '
        $0==b {skip=1; next}
        skip && $0==e {skip=0; next}
        !skip {print}
    ' "$cfg" > "$tmp"
    cat "$tmp" > "$cfg"
    rm -f "$tmp"
}

plugin_orcid() {
    require_engine
    local cfg
    cfg="$(engine_dir)/dspace/config/local.cfg"
    [ -f "$cfg" ] || error "local.cfg not found for '$DEPLOY_NAME' ($cfg). Deploy first."

    local action="enable" env="sandbox" client_id="" restart=1
    local client_secret="${ORCID_CLIENT_SECRET:-}"
    while [ $# -gt 0 ]; do
        case "$1" in
            --client-id)         client_id="$2"; shift 2 ;;
            --client-secret)     client_secret="$2"; shift 2 ;;
            --sandbox)           env="sandbox"; shift ;;
            --production|--live) env="production"; shift ;;
            --status)            action="status"; shift ;;
            --disable|--off)     action="disable"; shift ;;
            --no-restart)        restart=0; shift ;;
            *) error "Unknown option for orcid: $1" ;;
        esac
    done

    # The redirect URI DSpace advertises; it MUST be registered with the ORCID
    # app or the OAuth handshake is rejected.
    local server_url redirect
    server_url="$(grep -sE '^dspace\.server\.url[[:space:]]*=' "$cfg" | head -1 | cut -d= -f2- | tr -d ' ')"
    redirect="${server_url%/}/api/authn/orcid"

    case "$action" in
      status)
        if grep -qF "$ORCID_MARK_BEGIN" "$cfg"; then
            local cur_env cur_id
            if grep -sE '^orcid\.domain-url' "$cfg" | grep -q sandbox; then
                cur_env="sandbox"
            else
                cur_env="production"
            fi
            cur_id="$(grep -sE '^orcid\.application-client-id' "$cfg" | tail -1 | cut -d= -f2- | tr -d ' ')"
            echo -e "${GREEN}✓${NC} ORCID is ENABLED for '$DEPLOY_NAME'"
            echo "    Environment  : $cur_env"
            echo "    Client ID    : ${cur_id:-(unset)}"
            echo "    Redirect URI : $redirect"
        else
            echo -e "${YELLOW}○${NC} ORCID is not configured for '$DEPLOY_NAME' (password login only)."
            echo "    Enable it: chengetai orcid $DEPLOY_NAME --client-id APP-XXXX --client-secret SECRET"
        fi
        return 0 ;;
      disable)
        _orcid_strip "$cfg"
        info "ORCID disabled for '$DEPLOY_NAME' (managed block removed; password login remains)."
        if [ "$restart" = 1 ] && container_running dspace; then
            info "Restarting the backend to apply..."
            pcompose restart dspace
        fi
        return 0 ;;
    esac

    # enable
    [ -n "$client_id" ] || error "ORCID needs --client-id APP-XXXX (from ORCID → Developer Tools)."
    [ -n "$client_secret" ] || error "ORCID needs --client-secret (or export ORCID_CLIENT_SECRET to keep it out of shell history)."

    local domain api public
    if [ "$env" = "production" ]; then
        domain="https://orcid.org"
        api="https://api.orcid.org/v3.0"
        public="https://pub.orcid.org/v3.0"
    else
        domain="https://sandbox.orcid.org"
        api="https://api.sandbox.orcid.org/v3.0"
        public="https://pub.sandbox.orcid.org/v3.0"
    fi

    _orcid_strip "$cfg"   # clear any previous managed block, then write fresh
    {
        echo ""
        echo "$ORCID_MARK_BEGIN"
        echo "# ORCID sign-in + researcher identity. Environment: $env"
        echo "orcid.application-client-id = $client_id"
        echo "orcid.application-client-secret = $client_secret"
        echo "orcid.domain-url = $domain"
        echo "orcid.api-url = $api"
        echo "orcid.public-url = $public"
        echo "orcid.synchronization-enabled = true"
        echo "plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.PasswordAuthentication, org.dspace.authenticate.OrcidAuthentication"
        echo "$ORCID_MARK_END"
    } >> "$cfg"

    echo ""
    info "ORCID ($env) configured for '$DEPLOY_NAME'."
    echo ""
    echo "  ➜ Register this EXACT redirect URI in your ORCID app"
    echo "    (ORCID → Developer Tools → your application → Redirect URIs):"
    echo ""
    echo "        $redirect"
    echo ""
    echo "    Client ID : $client_id"
    echo "    Secret    : stored in $cfg"
    echo ""
    if [ "$restart" = 1 ]; then
        if container_running dspace; then
            info "Restarting the backend to apply (first boot after a config change can take a few minutes)..."
            pcompose restart dspace
            echo ""
            info "Done. Users will see 'Sign in with ORCID' at http://$(plugin_server_ip):$(ui_port)"
        else
            warn "Backend not running — start it to apply: chengetai start $DEPLOY_NAME"
        fi
    else
        info "Config written. Apply with: chengetai restart $DEPLOY_NAME"
    fi
}

# Copy this deployment's branding over the engine's assets. The engine's
# own copies are reset from git first so upstream updates never conflict
# with local branding.
apply_branding() {
    local engine brand
    engine=$(engine_dir)
    brand=$(branding_dir)

    if [ ! -d "$brand" ]; then
        mkdir -p "$brand"
        cp "$TEMPLATES_DIR/dspace/branding/"* "$brand/" 2>/dev/null || true
    fi

    git -C "$engine" checkout -- assets 2>/dev/null || true
    [ -f "$brand/logo.png" ]    && cp "$brand/logo.png"    "$engine/assets/bpoly-logo.png"
    [ -f "$brand/favicon.png" ] && cp "$brand/favicon.png" "$engine/assets/favicon.png"
}

plugin_deploy() {
    local engine
    engine=$(engine_dir)

    # 1. Clone (or reuse) the canonical repository. Its installer handles
    #    its own updates on re-runs.
    if [ ! -d "$engine/.git" ]; then
        if [ -e "$engine" ]; then
            error "Deployment '$DEPLOY_NAME' has a legacy engine directory. Back up its data, then: chengetai remove $DEPLOY_NAME && chengetai deploy $DEPLOY_NAME"
        fi
        info "Downloading deployment engine (canonical DSpace repository)..."
        git clone --depth 1 -b "$ENGINE_BRANCH" "$ENGINE_REPO" "$engine"
    fi

    # 2. Brand.
    apply_branding

    # 3+4. Configure & deploy: the reference installer does the real work.
    #      The profile flows in through its documented environment
    #      contract; COMPOSE_PROJECT_NAME namespaces volumes per
    #      deployment. It only prompts for whatever is missing (the
    #      admin password, unless ADMIN_PASS is set).
    UI_PORT="$(ui_port)" \
    REST_PORT="$(rest_port)" \
    DSPACE_NAME="${REPOSITORY:-$INSTITUTION}" \
    COMPOSE_PROJECT_NAME="chengetai-$DEPLOY_NAME" \
    INSTALL_DIR="$engine" \
        bash "$engine/install.sh"
}

# Point the deployment's public URL at an HTTPS domain — used by
# `chengetai domain`, which puts Caddy in front. Rewrites the frontend
# config.yml (ui + rest blocks) and the backend compose env, then rebuilds
# the frontend image and recreates the stack. Backups (.bak) are kept so the
# change is easy to roll back.
plugin_domain() {
    require_engine
    local domain="${1:-}"
    [ -n "$domain" ] || error "plugin_domain: a domain is required"

    local engine cfg compose
    engine="$(engine_dir)"
    cfg="$engine/config.yml"
    compose="$engine/docker-compose-campus.yml"

    # 1. Frontend: rewrite the ui: and rest: blocks to https://<domain>.
    if [ -f "$cfg" ]; then
        cp -f "$cfg" "$cfg.bak"
        awk -v d="$domain" '
            /^ui:/   { blk="ui";   print; next }
            /^rest:/ { blk="rest"; print; next }
            /^[^[:space:]]/ { blk="" }
            {
                if (blk=="ui" || blk=="rest") {
                    if ($1=="ssl:")  { print "  ssl: true"; next }
                    if ($1=="host:") { print "  host: " d;  next }
                    if ($1=="port:") { print "  port: 443"; next }
                }
                print
            }
        ' "$cfg.bak" > "$cfg"
        info "Frontend pointed at https://$domain (backup: config.yml.bak)"
    else
        warn "config.yml not found — skipping the frontend repoint."
    fi

    # 2. Backend: set the public server/ui URLs in the compose env.
    if [ -f "$compose" ]; then
        cp -f "$compose" "$compose.bak"
        sed -i -E "s#(dspace__P__server__P__url:).*#\1 https://$domain/server#" "$compose"
        sed -i -E "s#(dspace__P__ui__P__url:).*#\1 https://$domain#"          "$compose"
        if ! grep -q 'dspace__P__server__P__url' "$compose"; then
            warn "Backend server-URL env not found in compose — set dspace.server.url to https://$domain/server manually."
        else
            info "Backend public URL set to https://$domain/server (backup: docker-compose-campus.yml.bak)"
        fi
    else
        warn "docker-compose-campus.yml not found — skipping the backend repoint."
    fi

    # 3. Rebuild the frontend image (config.yml is baked in) and recreate.
    require_docker
    info "Rebuilding the frontend and recreating services (can take a few minutes)..."
    docker build -f "$engine/Dockerfile.angular" -t bpoly-dspace-angular:latest "$engine" >/dev/null
    pcompose up -d
    echo ""
    info "DSpace is now served at https://$domain"
}

plugin_start() {
    require_engine
    pcompose up -d
    echo ""
    info "Services started."
    echo ""
    plugin_urls
    echo ""
    echo "  The backend can take 3-5 minutes to come up."
    echo "  Check progress with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_stop() {
    require_engine
    # Containers are removed; the assetstore, database and Solr volumes are kept.
    pcompose down --remove-orphans
    echo ""
    info "All services stopped. Data volumes are preserved."
    echo "Start again with: chengetai start $DEPLOY_NAME"
    echo ""
}

plugin_restart() {
    require_engine
    pcompose restart
    echo ""
    info "Services restarted."
    echo "The backend can take 3-5 minutes to come up. Check with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_status() {
    require_engine
    pcompose ps

    local ip
    ip=$(plugin_server_ip)

    echo ""
    if curl -sf "http://localhost:$(rest_port)/server/api" >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} REST API       : http://${ip}:$(rest_port)/server"
    else
        echo -e "${RED}✗${NC} REST API       : not responding (http://${ip}:$(rest_port)/server)"
    fi

    if curl -sf "http://localhost:$(ui_port)" >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} User Interface : http://${ip}:$(ui_port)"
    else
        echo -e "${RED}✗${NC} User Interface : not responding (http://${ip}:$(ui_port))"
    fi
    echo ""
}

plugin_logs() {
    require_engine
    # Follows the whole stack, or only the services named as arguments.
    pcompose logs --tail=200 -f "$@"
}

plugin_backup() {
    require_engine
    if ! container_running dspacedb; then
        error "The database container (dspacedb) is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi
    if ! container_running dspace; then
        error "The backend container (dspace) is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi

    local dest
    dest="$DEPLOY_DIR/backups/chengetai-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$dest"

    info "Backing up database..."
    docker exec dspacedb pg_dump -U "$DB_USER" "$DB_NAME" | gzip > "$dest/dspace-db.sql.gz"

    info "Backing up assetstore (uploaded files)..."
    docker exec dspace tar czf - -C /dspace assetstore > "$dest/assetstore.tar.gz"

    echo ""
    info "Backup complete: $dest"
    du -sh "$dest"/* | sed 's/^/  /'
    echo ""
    echo "Restore later with: chengetai restore $DEPLOY_NAME $dest"
    echo ""
}

plugin_restore() {
    require_engine
    local backup="${1:-}"
    if [ -z "$backup" ]; then
        backup=$(ls -1d "$DEPLOY_DIR"/backups/chengetai-backup-* 2>/dev/null | sort | tail -1)
        [ -n "$backup" ] || error "No backups found in $DEPLOY_DIR/backups. Create one with: chengetai backup $DEPLOY_NAME"
        info "No backup specified — using most recent: $backup"
    fi

    local db_dump="$backup/dspace-db.sql.gz"
    local assets="$backup/assetstore.tar.gz"
    [ -f "$db_dump" ] || error "Database dump not found: $db_dump"
    [ -f "$assets" ] || error "Assetstore archive not found: $assets"

    if ! container_running dspacedb; then
        error "The database container (dspacedb) is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi

    echo "This will REPLACE the current database and all uploaded files"
    echo "with the contents of:"
    echo ""
    echo "  $backup"
    echo ""
    if ! confirm "Proceed with restore?"; then
        echo "Restore cancelled."
        exit 0
    fi

    info "Stopping backend and UI while restoring..."
    pcompose stop dspace dspace-angular

    info "Restoring database..."
    docker exec dspacedb psql -U "$DB_USER" -d postgres \
        -c "DROP DATABASE IF EXISTS $DB_NAME WITH (FORCE);"
    docker exec dspacedb psql -U "$DB_USER" -d postgres \
        -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
    docker exec dspacedb psql -U "$DB_USER" -d "$DB_NAME" \
        -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    gunzip -c "$db_dump" | docker exec -i dspacedb psql -q -U "$DB_USER" -d "$DB_NAME"

    info "Restoring assetstore (uploaded files)..."
    # The dspace container is stopped, so unpack into its assetstore volume
    # from a throwaway container that shares its volumes. The backend image
    # is already present locally, so nothing needs to be pulled.
    local image
    image=$(docker inspect dspace --format '{{.Config.Image}}')
    docker run --rm -i --volumes-from dspace --entrypoint bash "$image" \
        -c "rm -rf /dspace/assetstore/* && tar xzf - -C /dspace" < "$assets"

    info "Starting services..."
    pcompose start dspace dspace-angular

    echo ""
    info "Restore complete."
    echo "The backend can take 3-5 minutes to come up. Check with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_update() {
    require_engine
    local engine
    engine=$(engine_dir)

    info "Pulling latest canonical repository (branch: $ENGINE_BRANCH)..."
    git -C "$engine" checkout -- config.yml assets 2>/dev/null || true
    git -C "$engine" fetch origin "$ENGINE_BRANCH"
    git -C "$engine" pull --ff-only origin "$ENGINE_BRANCH"

    apply_branding

    info "Rebuilding branded frontend image..."
    docker build -f "$engine/Dockerfile.angular" -t bpoly-dspace-angular:latest "$engine"

    info "Applying update..."
    pcompose up -d --remove-orphans
}

# plugin_edit <component>
# Branding lives in deployments/<name>/branding/ and is applied over the
# engine on deploy/update, so canonical updates never conflict with it.
plugin_edit() {
    local component="$1" file

    case "$component" in
        logo)
            file="$(branding_dir)/logo.png"
            echo "The navbar logo is a PNG image (320x80 recommended):"
            echo ""
            echo "  $file"
            echo ""
            echo "Replace that file with your own PNG, then rebuild below."
            ;;
        favicon)
            file="$(branding_dir)/favicon.png"
            echo "The browser-tab icon is a PNG image (64x64 recommended):"
            echo ""
            echo "  $file"
            echo ""
            echo "Replace that file with your own PNG, then rebuild below."
            ;;
        config)
            require_engine
            file="$(engine_dir)/config.yml"
            [ -f "$file" ] || error "File not found: $file"
            echo "Opening: $file"
            echo ""
            "${EDITOR:-nano}" "$file"
            ;;
        communities)
            require_engine
            file="$(engine_dir)/setup-communities.sh"
            [ -f "$file" ] || error "File not found: $file"
            echo "Opening: $file"
            echo ""
            "${EDITOR:-nano}" "$file"
            ;;
        homepage|footer|news|css)
            error "'$component' cannot be edited: the frontend is a prebuilt image and only branding (logo, favicon, config) is replaceable. Editing page content requires a source build of dspace-angular."
            ;;
        *)
            error "Unknown component '$component'. Editable components: logo favicon config communities"
            ;;
    esac

    mkdir -p "$(branding_dir)"

    echo ""
    if confirm "Rebuild the frontend now so the change goes live?"; then
        require_docker
        require_engine
        apply_branding
        info "Rebuilding frontend..."
        docker build -f "$(engine_dir)/Dockerfile.angular" -t bpoly-dspace-angular:latest "$(engine_dir)"
        pcompose up -d dspace-angular
        echo ""
        info "Frontend rebuilt and restarted."
    else
        echo "Apply later with: chengetai update $DEPLOY_NAME"
    fi
}

# plugin_remove [purge]
# Stops and removes the containers; with purge=1 the data volumes
# (database, assetstore, Solr index) are deleted as well.
plugin_remove() {
    local purge="${1:-0}"
    if [ -f "$(engine_dir)/docker-compose-campus.yml" ]; then
        if [ "$purge" = "1" ]; then
            pcompose down --remove-orphans --volumes
        else
            pcompose down --remove-orphans
        fi
    fi
}
