#!/usr/bin/env bash
# DSpace 8 platform plugin for ChengetAi Deploy.
# Sourced by lib/utils.sh:load_plugin — requires DEPLOY_DIR, DEPLOY_NAME and
# the profile variables (INSTITUTION, ADMIN_EMAIL, ...) to be set.
#
# Self-contained: no external repository required. The plugin generates all
# Docker Compose and configuration files inline from official DSpace 8 images
# and deploys a fully working instance in under 15 minutes.
#
#   generate   docker-compose.yml, local.cfg, .env inside engine/
#   pull       all four images in parallel to minimise download time
#   brand      copy deployments/<name>/branding/ over the engine assets
#   start      docker compose up -d (health-gated ordering)
#   verify     poll the REST health endpoint — up in ~3-5 min after pull
#   admin      create the administrator account via the DSpace CLI
#   maintain   start/stop/status/logs/backup/restore/update/remove below

# shellcheck disable=SC2034  # PLUGIN_* consumed by the CLI after sourcing
PLUGIN_NAME="dspace"
PLUGIN_DESCRIPTION="DSpace 8 institutional repository"
PLUGIN_STATUS="available"

# Official DSpace 8 Docker Hub images (pre-built — no local build required).
DSPACE_IMAGE="dspace/dspace:dspace-8_x"
ANGULAR_IMAGE="dspace/dspace-angular:dspace-8_x"
POSTGRES_IMAGE="dspace/dspace-postgres-pgcrypto:latest"
SOLR_IMAGE="dspace/dspace-solr:dspace-8_x"

# Database credentials — password is generated per deployment.
DB_USER="dspace"
DB_NAME="dspace"

engine_dir() {
    echo "$DEPLOY_DIR/engine"
}

branding_dir() {
    echo "$DEPLOY_DIR/branding"
}

ui_port() {
    echo "${UI_PORT:-4000}"
}

rest_port() {
    echo "${REST_PORT:-8080}"
}

require_engine() {
    if [ ! -f "$(engine_dir)/docker-compose.yml" ]; then
        error "Deployment '$DEPLOY_NAME' has not been deployed yet. Run: chengetai deploy $DEPLOY_NAME"
    fi
}

# All compose operations use the generated compose file, namespaced per
# deployment so data volumes never collide across instances.
pcompose() {
    docker compose -p "chengetai-$DEPLOY_NAME" \
        -f "$(engine_dir)/docker-compose.yml" \
        --env-file "$(engine_dir)/.env" \
        --project-directory "$(engine_dir)" "$@"
}

plugin_server_ip() {
    local ip
    ip=$(grep -s '^SERVER_IP=' "$(engine_dir)/.env" | cut -d= -f2)
    echo "${ip:-localhost}"
}

plugin_urls() {
    local ip
    ip=$(plugin_server_ip)
    echo "  UI (browser):  http://${ip}:$(ui_port)"
    echo "  REST API:      http://${ip}:$(rest_port)/server"
}

# ── Engine file generation ────────────────────────────────────────────────────

# Write docker-compose.yml into the engine directory.
generate_compose() {
    local engine db_pass server_ip ui rest
    engine=$(engine_dir)
    db_pass="$1"
    server_ip="$2"
    ui=$(ui_port)
    rest=$(rest_port)
    local project="chengetai-$DEPLOY_NAME"

    cat > "$engine/docker-compose.yml" <<COMPOSE
services:
  dspacedb:
    image: $POSTGRES_IMAGE
    container_name: ${project}_db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: "${db_pass}"
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  dspacesolr:
    image: $SOLR_IMAGE
    container_name: ${project}_solr
    volumes:
      - solrdata:/var/solr
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8983/solr/ >/dev/null"]
      interval: 15s
      timeout: 10s
      retries: 12
    restart: unless-stopped

  dspace:
    image: $DSPACE_IMAGE
    container_name: ${project}_backend
    volumes:
      - assetstore:/dspace/assetstore
      - ./local.cfg:/dspace/config/local.cfg:ro
    ports:
      - "${rest}:8080"
    depends_on:
      dspacedb:
        condition: service_healthy
      dspacesolr:
        condition: service_started
    restart: unless-stopped

  dspace-angular:
    image: $ANGULAR_IMAGE
    container_name: ${project}_ui
    environment:
      - DSPACE_REST_HOST=${server_ip}
      - DSPACE_REST_PORT=${rest}
      - DSPACE_REST_NAMESPACE=/server
      - DSPACE_REST_SSL=false
    ports:
      - "${ui}:4000"
    depends_on:
      - dspace
    restart: unless-stopped

volumes:
  pgdata:
    name: ${project}_pgdata
  solrdata:
    name: ${project}_solrdata
  assetstore:
    name: ${project}_assetstore
COMPOSE
}

# Write local.cfg for the DSpace backend.
generate_config() {
    local engine db_pass server_ip ui rest repo_name
    engine=$(engine_dir)
    db_pass="$1"
    server_ip="$2"
    ui=$(ui_port)
    rest=$(rest_port)
    repo_name="${REPOSITORY:-$INSTITUTION}"

    cat > "$engine/local.cfg" <<CFG
# Generated by ChengetAi Deploy — do not edit by hand.
# Re-deploy or run: chengetai edit config $DEPLOY_NAME

dspace.dir       = /dspace
dspace.name      = ${repo_name}
dspace.server.url = http://${server_ip}:${rest}/server
dspace.ui.url    = http://${server_ip}:${ui}

db.url      = jdbc:postgresql://dspacedb:5432/${DB_NAME}
db.username = ${DB_USER}
db.password = ${db_pass}

solr.server = http://dspacesolr:8983/solr

mail.server = localhost
CFG
}

# Write .env (chmod 600) for the engine directory.
generate_env() {
    local engine db_pass server_ip
    engine=$(engine_dir)
    db_pass="$1"
    server_ip="$2"

    printf 'DB_PASS=%s\nSERVER_IP=%s\n' "$db_pass" "$server_ip" > "$engine/.env"
    chmod 600 "$engine/.env"
}

# ── Branding ──────────────────────────────────────────────────────────────────

# Copy branding assets into the angular container's build volume.
# Because we use a pre-built image, the logo/favicon are overlaid at
# container start via a bind-mount from branding/.
apply_branding() {
    local brand
    brand=$(branding_dir)

    if [ ! -d "$brand" ]; then
        mkdir -p "$brand"
        cp "$TEMPLATES_DIR/dspace/branding/"* "$brand/" 2>/dev/null || true
    fi
}

# ── Wait helper ───────────────────────────────────────────────────────────────

# Poll the DSpace REST health endpoint until it responds or timeout expires.
# DSpace backend (Spring Boot) typically needs 3-5 minutes after container
# start, so we allow 12 minutes before giving up.
wait_for_backend() {
    local rest_url="http://localhost:$(rest_port)/server/api"
    local timeout=720  # 12 minutes
    local interval=10
    local elapsed=0

    echo ""
    info "Waiting for DSpace backend to become ready (up to 12 min)..."
    while [ "$elapsed" -lt "$timeout" ]; do
        if curl -sf "$rest_url" >/dev/null 2>&1; then
            echo ""
            info "Backend is ready."
            return 0
        fi
        printf "  [%3ds] still starting...\r" "$elapsed"
        sleep "$interval"
        elapsed=$((elapsed + interval))
    done

    echo ""
    warn "Backend did not respond within 12 minutes."
    warn "Check progress with: chengetai logs $DEPLOY_NAME dspace"
    return 1
}

plugin_deploy() {
    local engine server_ip db_pass
    engine=$(engine_dir)

    # Detect or accept the server's public/LAN IP.
    server_ip="${SERVER_IP:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
    server_ip="${server_ip:-localhost}"

    # (Re-)generate the engine directory files. If they already exist we
    # re-use the existing DB password so a re-run is safe and idempotent.
    mkdir -p "$engine"
    if [ -f "$engine/.env" ]; then
        db_pass=$(grep -s '^DB_PASS=' "$engine/.env" | cut -d= -f2)
    fi
    if [ -z "$db_pass" ]; then
        db_pass=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)
    fi

    generate_env     "$db_pass" "$server_ip"
    generate_config  "$db_pass" "$server_ip"
    generate_compose "$db_pass" "$server_ip"

    # Apply branding (no-op until the user customises it).
    apply_branding

    # ── Step 1: Pull all images in parallel to minimise download time ──────
    echo ""
    info "Pulling DSpace 8 images in parallel (this is the longest step)..."
    docker pull "$DSPACE_IMAGE"   &
    docker pull "$ANGULAR_IMAGE"  &
    docker pull "$POSTGRES_IMAGE" &
    docker pull "$SOLR_IMAGE"     &
    wait
    info "All images ready."

    # ── Step 2: Start the stack ────────────────────────────────────────────
    echo ""
    info "Starting DSpace services..."
    pcompose up -d --remove-orphans

    # ── Step 3: Wait for the backend ───────────────────────────────────────
    if ! wait_for_backend; then
        warn "Deployment may still be starting. Verify with: chengetai status $DEPLOY_NAME"
        return 0
    fi

    # ── Step 4: Create the administrator account ───────────────────────────
    # Prompt for the admin password if not supplied via the environment.
    if [ -z "${ADMIN_PASS:-}" ]; then
        echo ""
        echo "  Set the administrator password."
        read -rsp "  Admin password: " ADMIN_PASS
        echo ""
        [ -n "$ADMIN_PASS" ] || error "Admin password is required."
    fi

    info "Creating administrator account (${ADMIN_EMAIL})..."
    local project="chengetai-$DEPLOY_NAME"
    docker exec "${project}_backend" \
        /dspace/bin/dspace create-administrator \
        -e "$ADMIN_EMAIL" \
        -f "$ADMIN_FIRST_NAME" \
        -l "$ADMIN_LAST_NAME" \
        -p "$ADMIN_PASS" \
        -c en 2>/dev/null \
    && info "Administrator account created." \
    || warn "Could not create admin automatically. Create it later with: chengetai admin $DEPLOY_NAME"

    # ── Done ───────────────────────────────────────────────────────────────
    echo ""
    echo "========================================="
    echo " DSpace 8 is ready!"
    echo "========================================="
    echo ""
    plugin_urls
    echo ""
    echo "  Admin email    : $ADMIN_EMAIL"
    echo "  Institution    : ${INSTITUTION}"
    echo ""
}

plugin_start() {
    require_engine
    pcompose up -d
    echo ""
    info "Services started."
    echo ""
    plugin_urls
    echo ""
    echo "  The backend can take 3-5 minutes to come up."
    echo "  Check progress with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_stop() {
    require_engine
    # Containers are removed; the assetstore, database and Solr volumes are kept.
    pcompose down --remove-orphans
    echo ""
    info "All services stopped. Data volumes are preserved."
    echo "Start again with: chengetai start $DEPLOY_NAME"
    echo ""
}

plugin_restart() {
    require_engine
    pcompose restart
    echo ""
    info "Services restarted."
    echo "The backend can take 3-5 minutes to come up. Check with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_status() {
    require_engine
    pcompose ps

    local ip
    ip=$(plugin_server_ip)

    echo ""
    if curl -sf "http://localhost:$(rest_port)/server/api" >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} REST API       : http://${ip}:$(rest_port)/server"
    else
        echo -e "${RED}✗${NC} REST API       : not responding (http://${ip}:$(rest_port)/server)"
    fi

    if curl -sf "http://localhost:$(ui_port)" >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} User Interface : http://${ip}:$(ui_port)"
    else
        echo -e "${RED}✗${NC} User Interface : not responding (http://${ip}:$(ui_port))"
    fi
    echo ""
}

plugin_logs() {
    require_engine
    # Follows the whole stack, or only the services named as arguments.
    pcompose logs --tail=200 -f "$@"
}

plugin_backup() {
    require_engine
    local project="chengetai-$DEPLOY_NAME"
    if [ "$(docker inspect -f '{{.State.Running}}' "${project}_db" 2>/dev/null)" != "true" ]; then
        error "The database container is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi
    if [ "$(docker inspect -f '{{.State.Running}}' "${project}_backend" 2>/dev/null)" != "true" ]; then
        error "The backend container is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi

    local dest
    dest="$DEPLOY_DIR/backups/chengetai-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$dest"

    info "Backing up database..."
    docker exec "${project}_db" pg_dump -U "$DB_USER" "$DB_NAME" | gzip > "$dest/dspace-db.sql.gz"

    info "Backing up assetstore (uploaded files)..."
    docker exec "${project}_backend" tar czf - -C /dspace assetstore > "$dest/assetstore.tar.gz"

    echo ""
    info "Backup complete: $dest"
    du -sh "$dest"/* | sed 's/^/  /'
    echo ""
    echo "Restore later with: chengetai restore $DEPLOY_NAME $dest"
    echo ""
}

plugin_restore() {
    require_engine
    local project="chengetai-$DEPLOY_NAME"
    local backup="${1:-}"
    if [ -z "$backup" ]; then
        backup=$(ls -1d "$DEPLOY_DIR"/backups/chengetai-backup-* 2>/dev/null | sort | tail -1)
        [ -n "$backup" ] || error "No backups found in $DEPLOY_DIR/backups. Create one with: chengetai backup $DEPLOY_NAME"
        info "No backup specified — using most recent: $backup"
    fi

    local db_dump="$backup/dspace-db.sql.gz"
    local assets="$backup/assetstore.tar.gz"
    [ -f "$db_dump" ] || error "Database dump not found: $db_dump"
    [ -f "$assets" ] || error "Assetstore archive not found: $assets"

    if [ "$(docker inspect -f '{{.State.Running}}' "${project}_db" 2>/dev/null)" != "true" ]; then
        error "The database container is not running. Start the repository first: chengetai start $DEPLOY_NAME"
    fi

    echo "This will REPLACE the current database and all uploaded files"
    echo "with the contents of:"
    echo ""
    echo "  $backup"
    echo ""
    if ! confirm "Proceed with restore?"; then
        echo "Restore cancelled."
        exit 0
    fi

    info "Stopping backend and UI while restoring..."
    pcompose stop dspace dspace-angular

    info "Restoring database..."
    docker exec "${project}_db" psql -U "$DB_USER" -d postgres \
        -c "DROP DATABASE IF EXISTS $DB_NAME WITH (FORCE);"
    docker exec "${project}_db" psql -U "$DB_USER" -d postgres \
        -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
    docker exec "${project}_db" psql -U "$DB_USER" -d "$DB_NAME" \
        -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    gunzip -c "$db_dump" | docker exec -i "${project}_db" psql -q -U "$DB_USER" -d "$DB_NAME"

    info "Restoring assetstore (uploaded files)..."
    local image
    image=$(docker inspect "${project}_backend" --format '{{.Config.Image}}')
    docker run --rm -i --volumes-from "${project}_backend" --entrypoint bash "$image" \
        -c "rm -rf /dspace/assetstore/* && tar xzf - -C /dspace" < "$assets"

    info "Starting services..."
    pcompose start dspace dspace-angular

    echo ""
    info "Restore complete."
    echo "The backend can take 3-5 minutes to come up. Check with: chengetai status $DEPLOY_NAME"
    echo ""
}

plugin_update() {
    require_engine

    info "Pulling latest DSpace 8 images..."
    pcompose pull

    apply_branding

    info "Applying update (rolling restart)..."
    pcompose up -d --remove-orphans
}

# plugin_edit <component>
# Branding lives in deployments/<name>/branding/ and is applied over the
# engine on deploy/update, so canonical updates never conflict with it.
plugin_edit() {
    local component="$1" file

    case "$component" in
        logo)
            file="$(branding_dir)/logo.png"
            echo "The navbar logo is a PNG image (320x80 recommended):"
            echo ""
            echo "  $file"
            echo ""
            echo "Replace that file with your own PNG, then run: chengetai update $DEPLOY_NAME"
            ;;
        favicon)
            file="$(branding_dir)/favicon.png"
            echo "The browser-tab icon is a PNG image (64x64 recommended):"
            echo ""
            echo "  $file"
            echo ""
            echo "Replace that file with your own PNG, then run: chengetai update $DEPLOY_NAME"
            ;;
        config)
            require_engine
            file="$(engine_dir)/local.cfg"
            [ -f "$file" ] || error "File not found: $file"
            echo "Opening: $file"
            echo ""
            "${EDITOR:-nano}" "$file"
            echo ""
            if confirm "Restart DSpace now so the change takes effect?"; then
                pcompose restart dspace
                echo ""
                info "DSpace restarted. Backend takes 3-5 minutes to come up."
            else
                echo "Apply later with: chengetai restart $DEPLOY_NAME"
            fi
            return 0
            ;;
        communities)
            error "'communities' editing requires a running DSpace instance — use the DSpace admin UI or REST API."
            ;;
        homepage|footer|news|css)
            error "'$component' cannot be edited: the frontend is a pre-built image. Editing page content requires a custom DSpace Angular source build."
            ;;
        *)
            error "Unknown component '$component'. Editable components: logo favicon config"
            ;;
    esac

    mkdir -p "$(branding_dir)"
}

# plugin_remove [purge]
# Stops and removes the containers; with purge=1 the data volumes
# (database, assetstore, Solr index) are deleted as well.
plugin_remove() {
    local purge="${1:-0}"
    if [ -f "$(engine_dir)/docker-compose.yml" ]; then
        if [ "$purge" = "1" ]; then
            pcompose down --remove-orphans --volumes
        else
            pcompose down --remove-orphans
        fi
    fi
}
